#project: USERNAME/PROJECT

name: airbus_ships_challenge
tags: [solution-4]

metric:
  channel: 'f2'
  goal: maximize

#Comment out if not in Cloud Environment
#pip-requirements-file: requirements.txt

exclude:
- .git
- .idea
- .ipynb_checkpoints
- output
- imgs
- neptune.log
- offline_job.log
- notebooks
- big-images-ids.csv
- big-images-ids_v2.csv

parameters:

  # Data Paths
  train_images_dir:     /public/challenges/kaggle-ship-detection/train
  test_images_dir:      /public/challenges/kaggle-ship-detection/test
  metadata_filepath:    /output/metadata.csv
  annotation_file:      /public/challenges/kaggle-ship-detection/train_ship_segmentations.csv
  masks_overlayed_dir:  /output/masks_overlayed

  # Execution
  num_workers: 4
  num_threads: 100
  image_source: disk
  pin_memory: 1
  loader_mode: resize
  resize_target_size: 256
  pad_method: symmetric
  target_format: 'joblib'
  dev_mode_size: 1000

  # General parameters
  image_h: 256
  image_w: 256
  image_channels: 3
  training_sampler_size: 7500
  training_sampler_empty_fraction: 0.0
  evaluation_size: 10000
  evaluation_empty_fraction: 0.52
  in_train_evaluation_size: 500
  fine_tuning: 1

  # Network parameters
  network_output_channels: 2
  network_activation: 'sigmoid'
  architecture: LargeKernelMatters
  encoder: DenseNet

  # Training schedule
  epochs_nr: 1000
  batch_size_train: 16
  batch_size_inference: 16
  lr: 0.0003
  momentum: 0.9
  gamma: 0.95
  patience: 20
  validation_metric_name: 'f2'
  minimize_validation_metric: 0
  reduce_factor: 0.5
  reduce_patience: 5
  min_lr: 0
  use_one_cycle: 1
  one_cycle_number_of_batches_per_full_cycle: 20000
  one_cycle_max_lr: 0.05

  # Regularization
  use_batch_norm: 1
  l2_reg_conv: 0.0001

  # Postprocessing
  threshold_masks: 0.44
  tta_aggregation_method: mean
  postpro__drop_size: 100
  postpro__mid_min_size: 0
  postpro__mid_max_size: 0

  # -------------------- SNS (SHIP NO SHIP) ----------------------

  # Network parameters
  sns_architecture: Densenet

  # Training schedule
  sns_training_sampler_empty_fracion: 0.52
  sns_epochs_nr: 100
  sns_batch_size_train: 64
  sns_batch_size_inference: 256
  sns_lr: 0.0001
  sns_momentum: 0.9
  sns_gamma: 0.95
  sns_patience: 5
  sns_validation_metric_name: 'sum'
  sns_minimize_validation_metric_name: 'sum'
  sns_minimize_validation_metric: 1
  sns_reduce_factor: 0.5
  sns_reduce_patience: 10
  sns_min_lr: 0
  sns_use_one_cycle: 1
  sns_one_cycle_number_of_batches_per_full_cycle: 10000
  sns_one_cycle_max_lr: 0.0001
  sns_image_h: 224
  sns_image_w: 224


  # Regularization
  sns_use_batch_norm: 1
  sns_l2_reg_conv: 0.0001

  # Postprocessing
  sns_threshold: 0.6